services:
  - type: web
    name: portofolio-main
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn portofolio_main.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portofolio_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "priesth13.onrender.com"