databases:
  - name: portofolio-db
    plan: free
    region: oregon

services:
  - type: web
    name: portofolio-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn portofolio_main.wsgi:application --chdir /opt/render/project/src --log-file -"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portofolio_main.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: portofolio-app.onrender.com,127.0.0.1
      - key: DATABASE_URL
        value: postgresql://portofolio_db_laqg_user:RoKrswhI3wmaOYpGjC2HJdy1JbtBQde9@dpg-d09atnh5pdvs73de8hs0-a.oregon-postgres.render.com/portofolio_db_laqg
      - key: GOOGLE_ANALYTICS_ID
        value: G-X7L9J96XSN
      - key: EMAIL_HOST_USER
        value: mateo.prifti13@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: nnhbrhlifgetogzw
      - key: DEFAULT_FROM_EMAIL
        value: mateo.prifti13@gmail.com
