# Generated by Django 4.2.20 on 2025-05-03 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port_mat', '0005_intro'),
    ]

    operations = [
    ]
